name: Publish Docker Image to GHCR

on:
  push:
    branches:
      - main  # Change to your preferred branch
  workflow_dispatch:

jobs:
  push_to_ghcr:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull Cloudbeaver Image
        run: docker pull dbeaver/cloudbeaver:23.2.5

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run Python script
        run: |
          cd ./AddNewDrivers && python ./AddNewDrivers.py 

      - name: Save Docker Image
        run: |
          docker commit cloudbeaver ghcr.io/dustin-jiang/cloudbeaver-opengauss:latest

      - name: Push Docker Image
        run: |
          docker push ghcr.io/dustin-jiang/cloudbeaver-opengauss:latest
